DROP TABLE tbTag;
DROP TABLE tbComment_Seq;
DROP TABLE tbCrewType_Seq;
DROP TABLE tbApplyMember_Seq;
DROP TABLE tbConfirmMember_Seq;
DROP TABLE tbMessengerList_Seq;
DROP TABLE tbMessenger_Seq;
DROP TABLE tbMessengerMember_Seq;
DROP TABLE tbShare_Seq;
DROP TABLE tbGoodBad_Seq;
DROP TABLE tbHit_Seq;
DROP TABLE tbImage_Seq;
DROP TABLE tbLocation_Seq;
DROP TABLE tbNotice_Seq;
DROP TABLE tbInterestCrew;
DROP TABLE tbMannerBadge;
DROP TABLE tbAttachment;
DROP TABLE tbCrewMemberList;
DROP TABLE tbChallengeFeed;
DROP TABLE tbCrewMemberFollower
DROP TABLE tbCrewChannelFollower
DROP TABLE tbBattleApplyCrewList
DROP TABLE tbBattleConfirmCrewList
DROP TABLE tbUserEvaluation;
DROP TABLE tbCrewEvaluation
DROP TABLE tbCrewChannel;
DROP TABLE tbCrewBattle;
DROP TABLE tbManagerBattle;
DROP TABLE tbLongCrew;
DROP TABLE tbOneDayCrew;
DROP TABLE tbCrewMemberInfo;


DROP SEQUENCE tbComment_Seq;
DROP SEQUENCE tbCrewType_Seq;
DROP SEQUENCE tbApplyMemberList_Seq;
DROP SEQUENCE tbConfirmMemberList_Seq;
DROP SEQUENCE tbMessengerList_Seq;
DROP SEQUENCE tbMessenger_Seq;
DROP SEQUENCE tbMessengerMember_Seq;
DROP SEQUENCE tbShare_Seq;
DROP SEQUENCE tbGoodBad_Seq;
DROP SEQUENCE tbHit_Seq;
DROP SEQUENCE tbImage_Seq;
DROP SEQUENCE tbLocation_Seq;
DROP SEQUENCE tbNotice_Seq;
DROP SEQUENCE tbTag_Seq;
DROP SEQUENCE tbInterestCrew_Seq;
DROP SEQUENCE tbMannerBadge_Seq;
DROP SEQUENCE tbAttachment_Seq;
DROP SEQUENCE tbCrewMemberList_Seq;
DROP SEQUENCE tbChallengeFeed_Seq;
DROP SEQUENCE tbCrewMemberFollower_Seq;
DROP SEQUENCE tbCrewChannelFollower_Seq;
DROP SEQUENCE tbBattleApplyCrewList_Seq;
DROP SEQUENCE tbBattleConfirmCrewList_Seq;
DROP SEQUENCE tbUserEvaluation_Seq;
DROP SEQUENCE tbCrewEvaluation_Seq;
DROP SEQUENCE tbCrewChannel_Seq;
DROP SEQUENCE tbCrewBattle_Seq;
DROP SEQUENCE tbManagerBattle_Seq;
DROP SEQUENCE tbLongCrew_Seq;
DROP SEQUENCE tbOneDayCrew_Seq;
DROP SEQUENCE tbCrewMemberInfo_Seq;